### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by GabrielLin** [jxhe/cross-lingual-struct-flow#3]
Thanks for your great work.

When I ran `python scripts/create_cwr.py --lang en`, the following errors were shown:

> Traceback (most recent call last):
>   File "scripts/create_cwr.py", line 93, in <module>
>     train_data = ConlluData(args.train_file, None, device=device)
>   File "/home4/xxx/air/jxhe-cross_lingual_struct_flow/modules/conllu_data.py", line 72, in __init__
>     embedding.append(self.text_to_embed(id_, sent_list, embed))
>   File "/home4/xxx/air/jxhe-cross_lingual_struct_flow/modules/conllu_data.py", line 105, in text_to_embed
>     sample = [embedding[word] if word in embedding else np.zeros(embedding.n_dim) for word in sent]
>   File "/home4/xxx/air/jxhe-cross_lingual_struct_flow/modules/conllu_data.py", line 105, in <listcomp>
>     sample = [embedding[word] if word in embedding else np.zeros(embedding.n_dim) for word in sent]
> TypeError: argument of type 'NoneType' is not iterable
>

Could you please give me some suggestions? Thanks.

**Comment by jxhe** [comment]
Fixed by https://github.com/jxhe/cross-lingual-struct-flow/commit/3fe06acecd5699182b761f7da18ccf42401f3e94
